
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `starting_zones`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `starting_zones` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `class_id` tinyint(3) unsigned NOT NULL DEFAULT 255,
  `race_id` tinyint(3) unsigned NOT NULL DEFAULT 255,
  `choice` tinyint(3) unsigned NOT NULL DEFAULT 255,
  `zone_id` int(11) unsigned NOT NULL DEFAULT 253,
  `is_instance` tinyint(1) NOT NULL DEFAULT 0,
  `min_version` int(10) NOT NULL DEFAULT 0,
  `max_version` int(10) NOT NULL DEFAULT 0,
  `x` float NOT NULL DEFAULT -999999,
  `y` float NOT NULL DEFAULT -999999,
  `z` float NOT NULL DEFAULT -999999,
  `heading` float NOT NULL DEFAULT -999999,
  `deity` int(11) NOT NULL DEFAULT 255,
  `ruleflag` int(11) NOT NULL DEFAULT 0,
  `description` text COLLATE latin1_general_ci DEFAULT '',
  `start_alignment` tinyint(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `NewIndex` (`class_id`,`race_id`,`zone_id`,`choice`),
  KEY `FK_starting_zones` (`zone_id`),
  CONSTRAINT `FK_starting_zones` FOREIGN KEY (`zone_id`) REFERENCES `zones` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

